mydata<-read.csv("household_power_consumption.txt",header = TRUE, sep=";", as.is=TRUE)
mydata$dt<-strptime(paste(mydata$Date,mydata$Time),format = "%d/%m/%Y %H:%M:%S")
mysubset<-subset(mydata,mydata$dt>="2007/02/01"&mydata$dt<"2007/02/03")
library(lubridate)
wday(mysubset$dt, label=TRUE)
plot(x=mysubset$dt,y=mysubset$Sub_metering_1,ylab = "Enery sub metering",xlab = (""),type = "l",col="black")
lines(x=mysubset$dt,y=mysubset$Sub_metering_2,ylab = "Enery sub metering",xlab = (""),type = "l",col="red")
lines(x=mysubset$dt,y=mysubset$Sub_metering_3,ylab = "Enery sub metering",xlab = (""),type = "l",col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1, lwd=2)
png(filename = "Plot3.png",width = 480,height = 480)
plot(x=mysubset$dt,y=mysubset$Sub_metering_1,ylab = "Enery sub metering",xlab = (""),type = "l",col="black")
lines(x=mysubset$dt,y=mysubset$Sub_metering_2,ylab = "Enery sub metering",xlab = (""),type = "l",col="red")
lines(x=mysubset$dt,y=mysubset$Sub_metering_3,ylab = "Enery sub metering",xlab = (""),type = "l",col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1, lwd=2)
dev.off()
