mydata<-read.csv("household_power_consumption.txt",header = TRUE, sep=";", as.is=TRUE)
mydata$dt<-strptime(paste(mydata$Date,mydata$Time),format = "%d/%m/%Y %H:%M:%S")
mysubset<-subset(mydata,mydata$dt>="2007/02/01"&mydata$dt<"2007/02/03")
library(lubridate)
wday(mysubset$dt, label=TRUE)
plot(mysubset$dt,mysubset$Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = (""),type = "l")
png(filename = "Plot2.png",width = 480,height = 480)
plot(mysubset$dt,mysubset$Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = (""),type = "l")
dev.off()